package frc.robot.autobuilder;

import java.util.ArrayList;
import java.util.List;

import frc.robot.autobuilder.ParsedRepr.Instruction;
import frc.robot.autobuilder.ParsedRepr.Value;
import frc.robot.autobuilder.ParsedRepr.Value.Type;;

/**
 * Converts {@link Token Tokens} into {@link ParsedRepr.Instruction Instructions}, 
 * discarding semantically meaningless punctuation and extracting literal values 
 */
public class Parser 
{
  /** The tokens of the source text, generated by the {@link Tokeniser} */
  private final List<Token> source; 
  /** The list that the instructions are placed into as they're parsed */
  private final ArrayList<Instruction> instrs = new ArrayList<>();

  /** The index of the token currently being parsed */
  private int pos = 0;

  /** @param tokens The tokens for this parser to parse */
  public Parser(List<Token> tokens)
  {
    source = tokens;
  }

  /**
   * Runs the actual parsing process, iterating through the tokens and grouping them into instructions
   * @return The list of parsed instructions
   */
  public List<Instruction> parse()
  {
    // The Eof (end of file) token type is used to signal the end of the token list
    while (peek() != Token.Type.Eof)
      nextInstr();

    return instrs;
  }

  /** Parses one instruction starting at the current position and adds it to the list */
  private void nextInstr()
  {
    // Consume the next token, ensuring that it is Text (the name of this instruction)
    Token tok = advance();
    if (tok.type() != Token.Type.Text) 
    { 
      err("expected a name to begin instruction but found " + tok);
      return;
    }
    String name = tok.text();

    // Consume the next token, ensuring that it's either the start of the argument list, or the end of the instruction
    // This allows 0-argument instructions to not need parentheses
    tok = advance();
    if (tok.type() != Token.Type.LParen)
    {
      if (!endOfInstr(tok))
        err("expected `(` to begin arguments or `,` to end instruction but found " + tok);
      else 
        // If we are at the end of the instruction, add the 0-argument instruction to the list
        addInstr(name, List.of());
      return;
    }
    
    // Iterate through tokens and construct a list of arguments from them
    ArrayList<Value> args = new ArrayList<>();
    loop: while (true)
    {
      tok = advance();
      switch (tok.type())
      {
        // Extract relevant values from literal tokens and add them to the argument list
        // Bools are stored as their literal `on` or `off` value, and converted into Java booleans when accessed. 
        // This is used for better diagnostics
        case Num -> args.add(new Value(Type.Num, Double.parseDouble(tok.text())));
        case Bool -> args.add(new Value(Type.Bool, tok.text()));
        case Text -> args.add(new Value(Type.Text, tok.text()));
        // Exit the loop if we've reached the end of the argument list
        case RParen -> {break loop;}
        // Error if the token isn't an argument or the end of the argument list
        default -> 
        {
          err("expected argument or `)` to end arguments but found " + tok);
          return;
        }
      }
    }

    // Consume the next token, ensuring it properly terminates this instruction. 
    // Consuming it now ensures that the next instruction we parse doesn't have to worry about leading commas
    tok = advance();
    if (!endOfInstr(tok))
    {
      err("expected `,` to end instruction but found " + tok);
      return;
    }
    
    // Add the parsed instruction to the list
    addInstr(name, args);
  }

  /** 
   * Gets the current token in the source and advances our position, 
   * or returns a blank {@link Token.Type#Eof end of file} token if we're already past the end of the source 
   */
  private Token advance() 
  {
    return pos >= source.size() ? new Token(Token.Type.Eof, "") : source.get(pos++);
  }

  /** 
   * Gets the type of the current token in the source without advancing, 
   * or returns {@link Token.Type#Eof end of file} if we're already past the end of the source 
   */
  private Token.Type peek() 
  {
    return pos >= source.size() ? Token.Type.Eof : source.get(pos).type();
  }

  /**
   * Skips tokens until we have passed a token of provided type
   * @param target The token type to skip past
   */
  private void skipPast(Token.Type target)
  {
    // Consume tokens until we've consumed the target token type or we reach the end of the tokens
    Token.Type tok = advance().type();
    while (!(tok == target || tok == Token.Type.Eof))
      tok = advance().type();
  }

  /**
   * Helper to check whether the provided token signals the end of an instruction
   * @param tok The token to check
   * @return True if the provided token signals the end of an instruction (it's either {@link Token.Type#Comma Comma} or {@link Token.Type#Eof Eof})
   */
  private boolean endOfInstr(Token tok)
    {return (tok.type() == Token.Type.Comma || tok.type() == Token.Type.Eof);}

  /**
   * Helper to report an error and skip to the next instruction, ensuring we don't attempt to use an invalid instruction
   * @param message The error message to report
   */
  private void err(String message)
  {
    AutoBuilder.error(message);
    skipPast(Token.Type.Comma);
  }

  /**
   * Adds a new instruction to the list, reporting an error if the provided name is not a valid instruction type
   * @param name The name of the instruction to add
   * @param args The arguments to the instruction, which get converted from a List to an Array
   */
  private void addInstr(String name, List<Value> args) 
  {
    try 
    {
      instrs.add(new Instruction(Instruction.Type.valueOf(name), args.toArray(Value[]::new)));
    }
    catch (IllegalArgumentException e)
    {
      AutoBuilder.error(name + " is not a valid instruction");
    }
  }
}
