package frc.robot.util.autobuilder;

import java.util.List;
import java.util.function.Supplier;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import edu.wpi.first.wpilibj2.command.Command.InterruptionBehavior;

import com.ctre.phoenix6.swerve.SwerveDrivetrain.SwerveDriveState;

import frc.robot.commands.swerve.PathFollowDrive;
import frc.robot.constants.FieldConstants;
import frc.robot.constants.Path;
import frc.robot.subsystems.CommandSwerveDrivetrain;
import frc.robot.subsystems.Intake;
import frc.robot.util.FieldUtils;
import frc.robot.util.PBDash;
import frc.robot.util.autobuilder.ParsedRepr.*;

/** Builds the final auto command from a list of {@link ParsedRepr.Instruction Instructions} */
public class CommandGen 
{
  /* Robot related values used by the produced command */
  private final Supplier<SwerveDriveState> swerveStateSup;
  private final CommandSwerveDrivetrain s_Swerve;
  private final Intake s_Intake;

  /** The list of instructions, generated by the {@link Parser} */
  private final List<Instruction> source;
  /** The final command group that gets built from the instructions */
  private final SequentialCommandGroup commands = new SequentialCommandGroup();

  /** The current instruction being compiled */
  private Instruction instr;
  /** Used to track the pose the robot will be at over the course of the auto */
  private Pose2d currPose;

  /**
   * Creates a new command generator, storing all the provided robot values internally for use in the produced command
   * @param instrs The instructions to be compiled
   * @param swerveStateSup Swerve state supplier, used to get the robot's starting position and provided to driving-related commands
   * @param s_Swerve The swerve subsystem
   * @param s_Intake The intake subsystem
   */
  public CommandGen
  (
    List<Instruction> instrs,
    Supplier<SwerveDriveState> swerveStateSup,
    CommandSwerveDrivetrain s_Swerve, 
    Intake s_Intake
  )
  {
    source = instrs;
    this.swerveStateSup = swerveStateSup;
    this.s_Swerve = s_Swerve;
    this.s_Intake = s_Intake;
  }

  /**
   * Runs the actual compilation process, compiling each instruction into a command and adding that to the final command group
   * @return The final auto command
   */
  public Command compile()
  {
    // Initialise our starting pose based on where the robot currently is. If we're on red alliance, we rotate the pose to make it blue-relative
    currPose = FieldUtils.allianceRotatePose(swerveStateSup.get().Pose);

    // Iterate over each instruction, calling a seperate function that handles the actual compilation logic and handling any errors that arise
    // This design means that the actual compilation logic is seperated from the error handling, and doesn't have to consider them
    for (int pos = 0; pos < source.size(); pos++)
    {
      instr = source.get(pos);
      try 
      {
        compileInstr();
      }
      catch (TypeMismatchException e)
      {
        // Example output: "argument `false` of instruction 0 (`intake`) has type Text but should have type Bool"
        AutoBuilder.error
        (
          "argument `", 
          e.found.value(), 
          "` of instruction ",
          pos + 1, 
          " (`", 
          instr.type(), 
          "`) has type ", 
          e.found.type(), 
          " but should have type ", 
          e.expected
        );
      }
      catch (ArgCountException e) 
      {
        // Example output: "instruction 0 (`follow`) has 0 arguments but should have 1 arguments"
        AutoBuilder.error
        (
          "instruction ",
          pos + 1, 
          " (`", 
          instr.type(), 
          "`) has  ",
          e.found,
          " arguments but should have ",
          e.expected,
          " arguments"
        );
      }
    }

    return commands.withInterruptBehavior(InterruptionBehavior.kCancelIncoming);
  }

  /**
   * Performs the actual compilation logic for each instruction type, seperate from the error handling done in {@link #compile()} <p>
   * 
   * Most of the errors are handled as exceptions, which are thrown by helper methods
   * and implicitly get rethrown by this to be caught in {@link #compile()}
   */
  private void compileInstr() throws TypeMismatchException, ArgCountException
  {
    switch (instr.type())
    {
      // driveto(x y r) - Go to pose `x`, `y`, `r` (alliance origin relative). `r` optional, maintains current rotation if omitted
      case driveto -> 
      { 
        Rotation2d rotationTarget;
        // Some extra handling is required due to the optional argument
        if (instr.args().length > 2) 
        {
          assertArgCount(3);
          rotationTarget = Rotation2d.fromDegrees(instr.arg(2).asNum());
        }
        else
        {
          assertArgCount(2);
          rotationTarget = currPose.getRotation();
        }

        // Clamp the target pose to at least half a meter from the field walls and the midline for safety and to handle mis-inputs
        // If either value changes as a result of this clamping, we provide a warning but still continue
        double xArg = instr.arg(0).asNum();
        double x = MathUtil.clamp(xArg, 0.5, (FieldConstants.fieldCentre.getX()) - 0.5);
        if (x != xArg) {AutoBuilder.error("warning: x value `", xArg, "` was clamped to `", x, "`");}
        double yArg = instr.arg(1).asNum();
        double y = MathUtil.clamp(yArg, 0.5, FieldConstants.fieldWidth - 0.5);
        if (y != yArg) {AutoBuilder.error("warning: y value `", yArg, "` was clamped to `", y, "`");}

        currPose = new Pose2d(new Translation2d(x, y), rotationTarget);

        // All prior handling was done using a blue alliance origin pose, and we now rotate the pose to match our actual alliance
        commands.addCommands(new PathFollowDrive(s_Swerve, swerveStateSup, FieldUtils.allianceRotatePose(currPose)));
      }
      // driveby(x y) - Relative drive TODO document
      case driveby -> 
      {
        assertArgCount(2);

        Translation2d offset = new Translation2d(instr.arg(0).asNum(), instr.arg(1).asNum());

        currPose = new Pose2d(currPose.getTranslation().plus(offset), currPose.getRotation());

        // All prior handling was done using a blue alliance origin pose, and we now rotate the pose to match our actual alliance
        commands.addCommands(new PathFollowDrive(s_Swerve, swerveStateSup, FieldUtils.allianceRotatePose(currPose)));
      }
      // follow(n) - Follow the path with name `n` in Path.autoPaths
      case follow -> 
      {
        assertArgCount(1);

        var pathName = instr.arg(0).asText();
        var path = Path.autoPaths.get(pathName);

        if (path == null)
        {
          AutoBuilder.error("no path `" + pathName + "`");
          return;
        }

        currPose = path.targetPose();
        commands.addCommands(new PathFollowDrive(s_Swerve, swerveStateSup, path.allianceRotated()));
      }
      // waitfor(d) - Wait for duration `d`
      case waitfor -> 
      {
        assertArgCount(1);

        commands.addCommands(Commands.waitSeconds(instr.arg(0).asNum()));
      }
      // waituntil(d) - wait until time `d`
      case waituntil -> 
      {
        assertArgCount(1);

        double duration = instr.arg(0).asNum();
        commands.addCommands(Commands.waitUntil(() -> Timer.getMatchTime() < (15 - duration)));
      }
      // intake(b) - if `b` is `on`/true, deploys and runs intake. if `b` is `off`/false, stops intake (leaving it deployed)
      case intake -> 
      {
        assertArgCount(1);

        if (instr.arg(0).asBool()) 
          commands.addCommands(Commands.parallel(s_Intake.extendCommand(), s_Intake.startIntakeCommand()));
        else 
          commands.addCommands(s_Intake.stopIntakeCommand());
      }
      // passing(b) - sets auto passing on or off based on `b`
      case passing -> 
      {
        assertArgCount(1);

        boolean passState = instr.arg(0).asBool();
        commands.addCommands(Commands.runOnce(() -> PBDash.IO_AUTO_PASS.put(passState)));
      }
    }
  }

  /**
   * Throws an exception if the number of arguments in the current instruction is different from the provided value.
   * Used as a helper to allow ergonomic, one-line checking of argument counts
   * @param count How many arguments the current instruction should have
   * @throws ArgCountException
   */
  private void assertArgCount(int count) throws ArgCountException
  {
    if (instr.args().length != count) 
      throw new ArgCountException(count, instr.args().length);
  }
}
